### ISSUE TITLE
FFMPEG

### ISSUE THREAD

**Issue by thistlillo** [PatternConsulting/opencv#8]
Is it possible to use somehow ffmpeg for decoding video files with your binary library?

**Comment by davidshen84** [comment]
Hi @michaelahlers,

I think this scala code can serve as a sample. My system is Ubuntu 64bit, with latest ffmpeg build as shared library. This same code works if I load my own build opencv library. But it fails if it loads the library in the jar file.

I suspect the opencv library ship with this jar file does not have ffmpeg functions compiled/linked.

    import org.opencv.core.Core
    import org.opencv.core.{Mat, MatOfInt, MatOfKeyPoint}
    import org.opencv.features2d.{FeatureDetector, DescriptorExtractor, Features2d}
    import org.opencv.highgui.{Highgui, VideoCapture}

    import scala.collection.JavaConverters._


    object Hello {

      nu.pattern.OpenCV.loadShared()
      // System.loadLibrary(Core.NATIVE_LIBRARY_NAME)


      def main(args: Array[String]): Unit = {

        println("Hello, world!")

        val cap = new VideoCapture("assets/any-video.mp4")
        if(!cap.isOpened) {
          println("cannot open video.")
          System.exit(-1)
        }

        val frame = new Mat()
        Highgui.imwrite("out/frame.jpeg", frame)
        cap.release()
      }
